language: node_js
node_js:
  - 8
  - 10
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn test
  - yarn e2e
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - yarn coverage