language: node_js
node_js:
  - "8"
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test
  - npm run e2e
after_success:
  - npm run coverage